version: '3.8'

services:
  app:
    image: mcr.microsoft.com/devcontainers/base:debian
    volumes:
      - ${LOCAL_WORKSPACE_FOLDER:-../..}:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker-host.sock
    command: sleep infinity
    # network_mode: service:db

  # db:
  #   image: postgres:16
  #   restart: 'no'
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_USER: ${POSTGRES_USER-postgres}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD-postgres}
  #     POSTGRES_DB: ${POSTGRES_DB-postgres}

  # web:
  #   image: dpage/pgadmin4:latest
  #   restart: 'no'
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-postgres}
  #     PGADMIN_LISTEN_PORT: 80
  #     PGADMIN_LISTEN_ADDRESS: '0.0.0.0'
  #     PGADMIN_CONFIG_SERVER_MODE: 'False'
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "${PGADMIN_PORT:-15432}:80"

  # jaeger:
  #   image: jaegertracing/all-in-one:latest
  #   environment:
  #     - COLLECTOR_OTLP_ENABLED=true
  #   restart: 'no'
  #   ports:
  #     - 16686
  #     - 4317

networks:
  default:
    enable_ipv6: false

# volumes:
#   postgres-data:
#     name: product-discovery-core-postgres-data
#   pgadmin:
#     name: product-discovery-core-pgadmin-data
